
go:
	cat ../example.json | grep 0x
	python3 print_codepoint.py

run:
	#python3 ./give_codepoint.py ./abc.txt
	#python3 ./give_codepoint.py ./glyphlist_complete.txt
	python3 ./give_codepoint.py ./glyphlist.txt
